version: "3.7"

services:
  menu:
    container_name: admin_menu
    build:
      context: src
      args:
        project: Menu
    ports:
      - 5000:80

  authorization:
    container_name: admin_authorization
    build:
      context: src
      args:
        project: Authorization
    ports:
      - 5001:80

  transactions:
    container_name: admin_transactions
    build:
      context: src
      args:
        project: Transactions
    ports:
      - 5002:80

  users:
    container_name: admin_users
    build:
      context: src
      args:
        project: Users
    ports:
      - 5003:80

  admin:
    container_name: admin_app
    build:
      context: src
      args:
        project: Admin
    ports:
      - 5004:80
