version: "3.7"

services:
  admin:
    container_name: admin_app
    build:
      context: src
      args:
        project: Admin
    ports:
      - 5000:80
    links:
      - authorization
    depends_on:
      - authorization

  menu:
    container_name: admin_menu
    build:
      context: src
      args:
        project: Menu
    ports:
      - 5001:80

  authorization:
    container_name: admin_authorization
    build:
      context: src
      args:
        project: Authorization
    expose:
      - "5002"

  transactions:
    container_name: admin_transactions
    build:
      context: src
      args:
        project: Transactions
    ports:
      - 5003:80

  users:
    container_name: admin_users
    build:
      context: src
      args:
        project: Users
    ports:
      - 5004:80